twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        default_avatar: '/build/images/AvatarSilhouette-admin.jpg'
        default_contact_avatar: '/build/images/AvatarSilhouette-1.jpg'
