-- MySQL Script generated by MySQL Workbench
-- do 25 mei 2017 14:29:49 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pipel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pipel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pipel` DEFAULT CHARACTER SET latin1 ;
USE `pipel` ;

-- -----------------------------------------------------
-- Table `pipel`.`Gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipel`.`Gender` (
  `idGender` INT NOT NULL AUTO_INCREMENT,
  `GenderType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGender`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pipel`.`Contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipel`.`Contacts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `LastName` VARCHAR(50) CHARACTER SET 'utf8' NULL,
  `PhoneticName` VARCHAR(45) NULL,
  `Avatar` VARCHAR(100) CHARACTER SET 'utf8' NULL,
  `Note` MEDIUMTEXT NULL,
  `Gender_idGender` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Contacts_Gender1_idx` (`Gender_idGender` ASC),
  CONSTRAINT `fk_Contacts_Gender1`
    FOREIGN KEY (`Gender_idGender`)
    REFERENCES `pipel`.`Gender` (`idGender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `pipel`.`Socialmedias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipel`.`Socialmedias` (
  `idSocialmediaType` INT NOT NULL AUTO_INCREMENT,
  `SocialmediaName` VARCHAR(45) NOT NULL,
  `SocialmediaIcon` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSocialmediaType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pipel`.`Contacts_Socialmedias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipel`.`Contacts_Socialmedias` (
  `Contacts_id` INT(11) NOT NULL,
  `Socialmedias_idSocialmediaType` INT NOT NULL,
  `SocialmediaUrl` VARCHAR(45) NULL,
  PRIMARY KEY (`Contacts_id`, `Socialmedias_idSocialmediaType`),
  INDEX `fk_Contacts_has_Socialmedias_Socialmedias1_idx` (`Socialmedias_idSocialmediaType` ASC),
  INDEX `fk_Contacts_has_Socialmedias_Contacts_idx` (`Contacts_id` ASC),
  CONSTRAINT `fk_Contacts_has_Socialmedias_Contacts`
    FOREIGN KEY (`Contacts_id`)
    REFERENCES `pipel`.`Contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contacts_has_Socialmedias_Socialmedias1`
    FOREIGN KEY (`Socialmedias_idSocialmediaType`)
    REFERENCES `pipel`.`Socialmedias` (`idSocialmediaType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `pipel`.`Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipel`.`Groups` (
  `idGroups` INT NOT NULL AUTO_INCREMENT,
  `GroupName` VARCHAR(45) NULL,
  PRIMARY KEY (`idGroups`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pipel`.`Contacts_Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipel`.`Contacts_Groups` (
  `Contacts_id` INT(11) NOT NULL,
  `Groups_idGroups` INT NOT NULL,
  PRIMARY KEY (`Contacts_id`, `Groups_idGroups`),
  INDEX `fk_Contacts_has_Groups_Groups1_idx` (`Groups_idGroups` ASC),
  INDEX `fk_Contacts_has_Groups_Contacts1_idx` (`Contacts_id` ASC),
  CONSTRAINT `fk_Contacts_has_Groups_Contacts1`
    FOREIGN KEY (`Contacts_id`)
    REFERENCES `pipel`.`Contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contacts_has_Groups_Groups1`
    FOREIGN KEY (`Groups_idGroups`)
    REFERENCES `pipel`.`Groups` (`idGroups`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `pipel`.`PhonesTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipel`.`PhonesTypes` (
  `idPhones` INT NOT NULL AUTO_INCREMENT,
  `PhoneType` VARCHAR(45) NULL,
  PRIMARY KEY (`idPhones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pipel`.`Contacts_has_PhonesTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipel`.`Contacts_has_PhonesTypes` (
  `Contacts_id` INT(11) NOT NULL AUTO_INCREMENT,
  `PhonesTypes_idPhones` INT NOT NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  `Whatsapp` TINYINT(1) NULL,
  `Telegram` TINYINT(1) NULL,
  PRIMARY KEY (`Contacts_id`, `PhonesTypes_idPhones`),
  INDEX `fk_Contacts_has_PhonesTypes_PhonesTypes1_idx` (`PhonesTypes_idPhones` ASC),
  INDEX `fk_Contacts_has_PhonesTypes_Contacts1_idx` (`Contacts_id` ASC),
  CONSTRAINT `fk_Contacts_has_PhonesTypes_Contacts1`
    FOREIGN KEY (`Contacts_id`)
    REFERENCES `pipel`.`Contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contacts_has_PhonesTypes_PhonesTypes1`
    FOREIGN KEY (`PhonesTypes_idPhones`)
    REFERENCES `pipel`.`PhonesTypes` (`idPhones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pipel`.`Gender`
-- -----------------------------------------------------
START TRANSACTION;
USE `pipel`;
INSERT INTO `pipel`.`Gender` (`idGender`, `GenderType`) VALUES (1, 'Male');
INSERT INTO `pipel`.`Gender` (`idGender`, `GenderType`) VALUES (2, 'Female');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pipel`.`Contacts`
-- -----------------------------------------------------
START TRANSACTION;
USE `pipel`;
INSERT INTO `pipel`.`Contacts` (`id`, `FirstName`, `LastName`, `PhoneticName`, `Avatar`, `Note`, `Gender_idGender`) VALUES (1, 'Cameron', 'Johnsen', NULL, 'me.jpg', NULL, 1);
INSERT INTO `pipel`.`Contacts` (`id`, `FirstName`, `LastName`, `PhoneticName`, `Avatar`, `Note`, `Gender_idGender`) VALUES (2, 'Lynn', 'R. Mason', NULL, '2.jpg', NULL, 1);
INSERT INTO `pipel`.`Contacts` (`id`, `FirstName`, `LastName`, `PhoneticName`, `Avatar`, `Note`, `Gender_idGender`) VALUES (3, 'Kennith', 'B. Bogart', NULL, '3.jpg', NULL, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pipel`.`Socialmedias`
-- -----------------------------------------------------
START TRANSACTION;
USE `pipel`;
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (1, 'Minds', 'fa-lightbulb-o');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (2, 'Facebook', 'fa-facebook-official');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (3, 'Twitter', 'fa-twitter');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (4, 'Google-Plus', 'fa-google-plus');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (5, 'Deviantart', 'fa-deviantart');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (6, 'Behance', 'fa-behance');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (7, 'Dribbble', 'fa-dribbble');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (8, 'Foursquare', 'fa-foursquare');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (9, 'Github', 'fa-github');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (10, 'Gitlab', 'fa-gitlab');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (11, 'Instagram', 'fa-instagram');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (12, 'LinkedIn', 'fa-linkedin');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (13, 'Pinterest', 'fa-pinterest-square');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (14, 'PayPal', 'fa-paypal');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (15, 'Skype', 'fa-skype');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (16, 'Snapchat', 'fa-snapchat');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (17, 'Vimeo', 'fa-vimeo');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (18, 'Soundcloud', 'fa-soundcloud');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (19, 'Tumblr', 'fa-tumblr');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (20, 'Slack', 'fa-slack');
INSERT INTO `pipel`.`Socialmedias` (`idSocialmediaType`, `SocialmediaName`, `SocialmediaIcon`) VALUES (21, 'Trello', 'fa-trello');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pipel`.`Groups`
-- -----------------------------------------------------
START TRANSACTION;
USE `pipel`;
INSERT INTO `pipel`.`Groups` (`idGroups`, `GroupName`) VALUES (1, 'Favourites');
INSERT INTO `pipel`.`Groups` (`idGroups`, `GroupName`) VALUES (2, 'Friends');
INSERT INTO `pipel`.`Groups` (`idGroups`, `GroupName`) VALUES (3, 'Family');
INSERT INTO `pipel`.`Groups` (`idGroups`, `GroupName`) VALUES (4, 'Colleagues');
INSERT INTO `pipel`.`Groups` (`idGroups`, `GroupName`) VALUES (5, 'Customers');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pipel`.`PhonesTypes`
-- -----------------------------------------------------
START TRANSACTION;
USE `pipel`;
INSERT INTO `pipel`.`PhonesTypes` (`idPhones`, `PhoneType`) VALUES (1, 'Mobile');
INSERT INTO `pipel`.`PhonesTypes` (`idPhones`, `PhoneType`) VALUES (2, 'Work');
INSERT INTO `pipel`.`PhonesTypes` (`idPhones`, `PhoneType`) VALUES (3, 'Home');
INSERT INTO `pipel`.`PhonesTypes` (`idPhones`, `PhoneType`) VALUES (4, 'Instant messaging');

COMMIT;

